export const ClassesData = [
  {
    instructor: "Dr. Janet M.",
    dates: ["Lun", "Mer", "Ven", "Sam"],
    time: ["8:00", "9:00", "10:00", "20:00"],
    class: "Séance de Physiothérapie",
    category: "Physiothérapie",
    difficulty: "Débutant",
    location: "Studio TheraPilates",
    room: "Salle de Thérapie 1",
  },
  {
    instructor: "Dr. Lynn Y.",
    dates: ["Mar", "Jeu", "Dim"],
    time: ["8:00", "9:00", "10:00", "20:00"],
    class: "Pilates Thérapeutique",
    category: "Pilates Thérapeutique",
    difficulty: "Débutant",
    location: "Studio TheraPilates",
    room: "Salle Pilates",
  },
  {
    instructor: "Emma E.",
    dates: ["Mar", "Jeu"],
    time: ["11:00", "18:00"],
    class: "Pilates Prénatal",
    category: "Préparation à l'Accouchement",
    difficulty: "Débutant",
    location: "Studio TheraPilates",
    room: "Salle Pilates",
  },
  {
    instructor: "Emma E.",
    dates: ["Ven", "Sam"],
    time: ["8:00", "9:00", "11:00"],
    class: "Pilates Postnatal",
    category: "Récupération Postnatale",
    difficulty: "Débutant",
    location: "Studio TheraPilates",
    room: "Salle Pilates",
  },
  {
    instructor: "June P.",
    dates: ["Lun", "Sam", "Dim"],
    time: ["8:00", "9:00", "11:00", "18:00"],
    class: "Pilates de Rééducation",
    category: "Rééducation après Blessure",
    difficulty: "Intermédiaire",
    location: "Studio TheraPilates",
    room: "Salle de Thérapie 2",
  },
  {
    instructor: "Dania M.",
    dates: ["Lun", "Mer", "Dim"],
    time: ["8:00", "9:00", "10:00", "20:00"],
    class: "Pilates Thérapeutique Avancé",
    category: "Pilates Thérapeutique",
    difficulty: "Intermédiaire",
    location: "Studio TheraPilates",
    room: "Salle Pilates",
  },
];
