export const ClassesData = [
  {
    instructor: "Dr. Janet M.",
    dates: ["Mon", "Wed", "Fri", "Sat"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "Physiotherapy Session",
    category: "Physiotherapy",
    difficulty: "Beginner",
    location: "TheraPilates Studio",
    room: "Therapy Room 1",
  },
  {
    instructor: "Dr. Lynn Y.",
    dates: ["Tue", "Thu", "Sun"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "Therapeutic Pilates",
    category: "Therapeutic Pilates",
    difficulty: "Beginner",
    location: "TheraPilates Studio",
    room: "Pilates Studio Room",
  },
  {
    instructor: "Emma E.",
    dates: ["Tue", "Thu"],
    time: ["11:00AM", "6:00PM"],
    class: "Prenatal Pilates",
    category: "Preparation for Childbirth",
    difficulty: "Beginner",
    location: "TheraPilates Studio",
    room: "Pilates Studio Room",
  },
  {
    instructor: "Emma E.",
    dates: ["Fri", "Sat"],
    time: ["8:00AM", "9:00AM", "11:00AM"],
    class: "Postnatal Pilates",
    category: "Postnatal Recovery",
    difficulty: "Beginner",
    location: "TheraPilates Studio",
    room: "Pilates Studio Room",
  },
  {
    instructor: "June P.",
    dates: ["Mon", "Sat", "Sun"],
    time: ["8:00AM", "9:00AM", "11:00AM", "6:00PM"],
    class: "Rehabilitation Pilates",
    category: "Injury Rehabilitation",
    difficulty: "Intermediate",
    location: "TheraPilates Studio",
    room: "Therapy Room 2",
  },
  {
    instructor: "Dania M.",
    dates: ["Mon", "Wed", "Sun"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "Therapeutic Pilates Advanced",
    category: "Therapeutic Pilates",
    difficulty: "Intermediate",
    location: "TheraPilates Studio",
    room: "Pilates Studio Room",
  },
];
