export const ClassesData = [
  {
    instructor: "Janet M.",
    dates: ["Mon", "Wed", "Fri", "Sat"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "MOVE Control",
    category: "Reformer Pilates",
    difficulty: "Beginner",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
  {
    instructor: "Lynn Y.",
    dates: ["Tue", "Thu", "Sun"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "MOVE Control",
    category: "Reformer Pilates",
    difficulty: "Beginner",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
  {
    instructor: "Emma E.",
    dates: ["Tue", "Thu"],
    time: ["11:00AM", "6:00PM"],
    class: "MOVE Burn (INT)",
    category: "Reformer Pilates (Intermediate)",
    difficulty: "Intermediate",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
  {
    instructor: "Emma E.",
    dates: ["Fri", "Sat"],
    time: ["8:00AM", "9:00AM", "11:00AM"],
    class: "MOVE Chair",
    category: "Chair Pilates",
    difficulty: "Beginner",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
  {
    instructor: "June P.",
    dates: ["Mon", "Sat", "Sun"],
    time: ["8:00AM", "9:00AM", "11:00AM", "6:00PM"],
    class: "MOVE Jump",
    category: "Reformer Pilates (Intermediate)",
    difficulty: "Intermediate",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
  {
    instructor: "Dania M.",
    dates: ["Mon", "Wed", "Sun"],
    time: ["8:00AM", "9:00AM", "10:00AM", "8:00PM"],
    class: "MOVE Chair",
    category: "Reformer Pilates",
    difficulty: "Beginner",
    location: "MOVE Pilates Studio",
    room: "Reformer Pilates Group Room",
  },
];
