const packageData = [
  {
    category: "intro",
    categoryTitle: "INTRO PACK - NEW CLIENTS",
    packageTitle: "Starter Pack: 3 Sessions",
    packagePrice: "TND 180",
    paymentSched: "One time payment",
    credits: "3 credits for sessions",
    access: "All location access",
    validity: "Valid for 1 month from the date of first booking",
    paymentLink: "/checkout-intro",
  },
  {
    category: "class",
    categoryTitle: "SESSION PACK",
    packageTitle: "Drop-in: One Session",
    packagePrice: "TND 85",
    paymentSched: "One time payment",
    credits: "1 credit for sessions",
    access: "All location access",
    validity: "Valid for 1 month from the date of first booking",
    paymentLink: "/checkout-dropin",
  },
  {
    category: "class",
    categoryTitle: "SESSION PACK",
    packageTitle: "4 Sessions",
    packagePrice: "TND 310",
    paymentSched: "One time payment",
    credits: "4 credits for sessions",
    access: "All location access",
    validity: "Valid for 1 month from the date of first booking",
    paymentLink: "/checkout-fourclasses",
  },
  {
    category: "share",
    categoryTitle: "SHAREABLE FOR 2",
    packageTitle: "25 Sessions",
    packagePrice: "TND 1,750",
    paymentSched: "One time payment",
    credits: "25 credits for sessions",
    access: "All location access",
    validity: "Valid for 6 months from the date of first booking",
    paymentLink: "/checkout-25classes",
  },
];

export default packageData;
